// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: components/users/pb/user.proto

package pb

import (
	kube "github.com/justinsb/kweb/components/kube"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Typemeta *kube.TypeMeta   `protobuf:"bytes,1,opt,name=typemeta,proto3" json:"typemeta,omitempty"`
	Metadata *kube.ObjectMeta `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec     *UserSpec        `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_components_users_pb_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_components_users_pb_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_components_users_pb_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetTypemeta() *kube.TypeMeta {
	if x != nil {
		return x.Typemeta
	}
	return nil
}

func (x *User) GetMetadata() *kube.ObjectMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *User) GetSpec() *UserSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type UserSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email          string           `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	LinkedAccounts []*LinkedAccount `protobuf:"bytes,2,rep,name=linked_accounts,json=linkedAccounts,proto3" json:"linked_accounts,omitempty"`
}

func (x *UserSpec) Reset() {
	*x = UserSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_components_users_pb_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSpec) ProtoMessage() {}

func (x *UserSpec) ProtoReflect() protoreflect.Message {
	mi := &file_components_users_pb_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSpec.ProtoReflect.Descriptor instead.
func (*UserSpec) Descriptor() ([]byte, []int) {
	return file_components_users_pb_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserSpec) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserSpec) GetLinkedAccounts() []*LinkedAccount {
	if x != nil {
		return x.LinkedAccounts
	}
	return nil
}

type LinkedAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The capitilization isn't normal proto, but it avoids name mangling
	ProviderID       string `protobuf:"bytes,2,opt,name=providerID,proto3" json:"providerID,omitempty"`
	ProviderUserID   string `protobuf:"bytes,3,opt,name=providerUserID,proto3" json:"providerUserID,omitempty"`
	ProviderUserName string `protobuf:"bytes,4,opt,name=providerUserName,proto3" json:"providerUserName,omitempty"`
}

func (x *LinkedAccount) Reset() {
	*x = LinkedAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_components_users_pb_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkedAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkedAccount) ProtoMessage() {}

func (x *LinkedAccount) ProtoReflect() protoreflect.Message {
	mi := &file_components_users_pb_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkedAccount.ProtoReflect.Descriptor instead.
func (*LinkedAccount) Descriptor() ([]byte, []int) {
	return file_components_users_pb_user_proto_rawDescGZIP(), []int{2}
}

func (x *LinkedAccount) GetProviderID() string {
	if x != nil {
		return x.ProviderID
	}
	return ""
}

func (x *LinkedAccount) GetProviderUserID() string {
	if x != nil {
		return x.ProviderUserID
	}
	return ""
}

func (x *LinkedAccount) GetProviderUserName() string {
	if x != nil {
		return x.ProviderUserName
	}
	return ""
}

var File_components_users_pb_user_proto protoreflect.FileDescriptor

var file_components_users_pb_user_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x75, 0x73, 0x65,
	0x72, 0x73, 0x2f, 0x70, 0x62, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x1a, 0x1a, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73,
	0x2f, 0x6b, 0x75, 0x62, 0x65, 0x2f, 0x6b, 0x75, 0x62, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x8e, 0x01, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x08, 0x74, 0x79, 0x70,
	0x65, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6b, 0x75,
	0x62, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x08, 0x74, 0x79, 0x70,
	0x65, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x2c, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6b, 0x75, 0x62, 0x65, 0x2e, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x20, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x70, 0x65, 0x63, 0x52,
	0x04, 0x73, 0x70, 0x65, 0x63, 0x3a, 0x0a, 0x8a, 0xb5, 0x18, 0x06, 0x0a, 0x04, 0x55, 0x73, 0x65,
	0x72, 0x22, 0x5c, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x53, 0x70, 0x65, 0x63, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x3a, 0x0a, 0x0f, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x5f, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70,
	0x62, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x0e, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x22,
	0x83, 0x01, 0x0a, 0x0d, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x2a, 0x0a, 0x10, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x10, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x55, 0x73, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x81, 0x01, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x62,
	0x42, 0x09, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2c, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x75, 0x73, 0x74, 0x69, 0x6e,
	0x73, 0x62, 0x2f, 0x6b, 0x77, 0x65, 0x62, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x70, 0x62, 0xa2, 0x02, 0x03, 0x50, 0x58,
	0x58, 0xaa, 0x02, 0x02, 0x50, 0x62, 0xca, 0x02, 0x02, 0x50, 0x62, 0xe2, 0x02, 0x0e, 0x50, 0x62,
	0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x02, 0x50,
	0x62, 0x82, 0xb5, 0x18, 0x14, 0x0a, 0x08, 0x6b, 0x77, 0x65, 0x62, 0x2e, 0x64, 0x65, 0x76, 0x12,
	0x08, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_components_users_pb_user_proto_rawDescOnce sync.Once
	file_components_users_pb_user_proto_rawDescData = file_components_users_pb_user_proto_rawDesc
)

func file_components_users_pb_user_proto_rawDescGZIP() []byte {
	file_components_users_pb_user_proto_rawDescOnce.Do(func() {
		file_components_users_pb_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_components_users_pb_user_proto_rawDescData)
	})
	return file_components_users_pb_user_proto_rawDescData
}

var file_components_users_pb_user_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_components_users_pb_user_proto_goTypes = []interface{}{
	(*User)(nil),            // 0: pb.User
	(*UserSpec)(nil),        // 1: pb.UserSpec
	(*LinkedAccount)(nil),   // 2: pb.LinkedAccount
	(*kube.TypeMeta)(nil),   // 3: kube.TypeMeta
	(*kube.ObjectMeta)(nil), // 4: kube.ObjectMeta
}
var file_components_users_pb_user_proto_depIdxs = []int32{
	3, // 0: pb.User.typemeta:type_name -> kube.TypeMeta
	4, // 1: pb.User.metadata:type_name -> kube.ObjectMeta
	1, // 2: pb.User.spec:type_name -> pb.UserSpec
	2, // 3: pb.UserSpec.linked_accounts:type_name -> pb.LinkedAccount
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_components_users_pb_user_proto_init() }
func file_components_users_pb_user_proto_init() {
	if File_components_users_pb_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_components_users_pb_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_components_users_pb_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_components_users_pb_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkedAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_components_users_pb_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_users_pb_user_proto_goTypes,
		DependencyIndexes: file_components_users_pb_user_proto_depIdxs,
		MessageInfos:      file_components_users_pb_user_proto_msgTypes,
	}.Build()
	File_components_users_pb_user_proto = out.File
	file_components_users_pb_user_proto_rawDesc = nil
	file_components_users_pb_user_proto_goTypes = nil
	file_components_users_pb_user_proto_depIdxs = nil
}
