// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: components/users/pb/user.proto

package pb

import (
	kube "github.com/justinsb/kweb/components/kube"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Typemeta *kube.TypeMeta   `protobuf:"bytes,1,opt,name=typemeta,proto3" json:"typemeta,omitempty"`
	Metadata *kube.ObjectMeta `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec     *UserSpec        `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_components_users_pb_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_components_users_pb_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_components_users_pb_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetTypemeta() *kube.TypeMeta {
	if x != nil {
		return x.Typemeta
	}
	return nil
}

func (x *User) GetMetadata() *kube.ObjectMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *User) GetSpec() *UserSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type UserSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *UserSpec) Reset() {
	*x = UserSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_components_users_pb_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSpec) ProtoMessage() {}

func (x *UserSpec) ProtoReflect() protoreflect.Message {
	mi := &file_components_users_pb_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSpec.ProtoReflect.Descriptor instead.
func (*UserSpec) Descriptor() ([]byte, []int) {
	return file_components_users_pb_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserSpec) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UserAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Typemeta *kube.TypeMeta   `protobuf:"bytes,1,opt,name=typemeta,proto3" json:"typemeta,omitempty"`
	Metadata *kube.ObjectMeta `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec     *UserAuthSpec    `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
}

func (x *UserAuth) Reset() {
	*x = UserAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_components_users_pb_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuth) ProtoMessage() {}

func (x *UserAuth) ProtoReflect() protoreflect.Message {
	mi := &file_components_users_pb_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuth.ProtoReflect.Descriptor instead.
func (*UserAuth) Descriptor() ([]byte, []int) {
	return file_components_users_pb_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserAuth) GetTypemeta() *kube.TypeMeta {
	if x != nil {
		return x.Typemeta
	}
	return nil
}

func (x *UserAuth) GetMetadata() *kube.ObjectMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UserAuth) GetSpec() *UserAuthSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type UserAuthSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The capitilization isn't normal proto, but it avoids name mangling
	UserID         string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ProviderID     string `protobuf:"bytes,2,opt,name=providerID,proto3" json:"providerID,omitempty"`
	ProviderUserID string `protobuf:"bytes,3,opt,name=providerUserID,proto3" json:"providerUserID,omitempty"`
}

func (x *UserAuthSpec) Reset() {
	*x = UserAuthSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_components_users_pb_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAuthSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuthSpec) ProtoMessage() {}

func (x *UserAuthSpec) ProtoReflect() protoreflect.Message {
	mi := &file_components_users_pb_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuthSpec.ProtoReflect.Descriptor instead.
func (*UserAuthSpec) Descriptor() ([]byte, []int) {
	return file_components_users_pb_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserAuthSpec) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UserAuthSpec) GetProviderID() string {
	if x != nil {
		return x.ProviderID
	}
	return ""
}

func (x *UserAuthSpec) GetProviderUserID() string {
	if x != nil {
		return x.ProviderUserID
	}
	return ""
}

var File_components_users_pb_user_proto protoreflect.FileDescriptor

var file_components_users_pb_user_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x75, 0x73, 0x65,
	0x72, 0x73, 0x2f, 0x70, 0x62, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x1a, 0x0a, 0x6b, 0x75, 0x62, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x8e, 0x01, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x08, 0x74, 0x79, 0x70,
	0x65, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6b, 0x75,
	0x62, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x08, 0x74, 0x79, 0x70,
	0x65, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x2c, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6b, 0x75, 0x62, 0x65, 0x2e, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x20, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x70, 0x65, 0x63, 0x52,
	0x04, 0x73, 0x70, 0x65, 0x63, 0x3a, 0x0a, 0x8a, 0xb5, 0x18, 0x06, 0x0a, 0x04, 0x55, 0x73, 0x65,
	0x72, 0x22, 0x20, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x53, 0x70, 0x65, 0x63, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x22, 0x9a, 0x01, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68,
	0x12, 0x2a, 0x0a, 0x08, 0x74, 0x79, 0x70, 0x65, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6b, 0x75, 0x62, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x4d, 0x65,
	0x74, 0x61, 0x52, 0x08, 0x74, 0x79, 0x70, 0x65, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x2c, 0x0a, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x6b, 0x75, 0x62, 0x65, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x61,
	0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x24, 0x0a, 0x04, 0x73, 0x70,
	0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x41, 0x75, 0x74, 0x68, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63,
	0x3a, 0x0e, 0x8a, 0xb5, 0x18, 0x0a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68,
	0x22, 0x6e, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68, 0x53, 0x70, 0x65, 0x63,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x49, 0x44, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x42, 0x43, 0x5a, 0x29, 0x73, 0x75, 0x62, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x76, 0x69, 0x64, 0x65,
	0x6f, 0x2f, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x6f,
	0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x82, 0xb5, 0x18,
	0x14, 0x0a, 0x08, 0x6b, 0x77, 0x65, 0x62, 0x2e, 0x64, 0x65, 0x76, 0x12, 0x08, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_components_users_pb_user_proto_rawDescOnce sync.Once
	file_components_users_pb_user_proto_rawDescData = file_components_users_pb_user_proto_rawDesc
)

func file_components_users_pb_user_proto_rawDescGZIP() []byte {
	file_components_users_pb_user_proto_rawDescOnce.Do(func() {
		file_components_users_pb_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_components_users_pb_user_proto_rawDescData)
	})
	return file_components_users_pb_user_proto_rawDescData
}

var file_components_users_pb_user_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_components_users_pb_user_proto_goTypes = []interface{}{
	(*User)(nil),            // 0: pb.User
	(*UserSpec)(nil),        // 1: pb.UserSpec
	(*UserAuth)(nil),        // 2: pb.UserAuth
	(*UserAuthSpec)(nil),    // 3: pb.UserAuthSpec
	(*kube.TypeMeta)(nil),   // 4: kube.TypeMeta
	(*kube.ObjectMeta)(nil), // 5: kube.ObjectMeta
}
var file_components_users_pb_user_proto_depIdxs = []int32{
	4, // 0: pb.User.typemeta:type_name -> kube.TypeMeta
	5, // 1: pb.User.metadata:type_name -> kube.ObjectMeta
	1, // 2: pb.User.spec:type_name -> pb.UserSpec
	4, // 3: pb.UserAuth.typemeta:type_name -> kube.TypeMeta
	5, // 4: pb.UserAuth.metadata:type_name -> kube.ObjectMeta
	3, // 5: pb.UserAuth.spec:type_name -> pb.UserAuthSpec
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_components_users_pb_user_proto_init() }
func file_components_users_pb_user_proto_init() {
	if File_components_users_pb_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_components_users_pb_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_components_users_pb_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_components_users_pb_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_components_users_pb_user_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAuthSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_components_users_pb_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_components_users_pb_user_proto_goTypes,
		DependencyIndexes: file_components_users_pb_user_proto_depIdxs,
		MessageInfos:      file_components_users_pb_user_proto_msgTypes,
	}.Build()
	File_components_users_pb_user_proto = out.File
	file_components_users_pb_user_proto_rawDesc = nil
	file_components_users_pb_user_proto_goTypes = nil
	file_components_users_pb_user_proto_depIdxs = nil
}
