apiVersion: v1
kind: Namespace
metadata:
  name: kweb-sso-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kweb-sso
  name: kweb-sso
  namespace: kweb-sso-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kweb-sso
  template:
    metadata:
      labels:
        app: kweb-sso
    spec:
      serviceAccountName: kweb-sso
      containers:
      - image: image-repo/kweb-sso:latest
        name: kweb-sso
        envFrom:
        - secretRef:
            name: kweb-sso
        - configMapRef:
            name: kweb-sso
        # readinessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: 8080
        #     scheme: HTTPS
        volumeMounts:
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: true
      volumes:
      - name: spire-agent-socket
        hostPath:
          path: /run/spire/sockets
          type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: kweb-sso
  namespace: kweb-sso-system
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: kweb-sso
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kweb-sso
  name: kweb-sso
  namespace: kweb-sso-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kweb-sso
  namespace: kweb-sso-system
rules:
- apiGroups: ["kweb.dev"]
  resources: ["users"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
# - apiGroups: [""]
#   resources: ["namespaces"]
#   verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kweb-sso
  namespace: kweb-sso-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kweb-sso
subjects:
- kind: ServiceAccount
  name: kweb-sso
  namespace: kweb-sso-system
